- hosts: remoto
  gather_facts: False
  debugger: on_skipped

  tasks:
  - name: Instalando mongo
    apt:
      name: mongo
      update_cache: yes
      state: present

  - name: Habilitar o Mongo no boot
    service:
        name: mongo
        enabled: yes
        state: started

  - name: Copiando artefatos para o servidor
    copy:
       src: "{{ item }}"
       dest: "/root/{{ item }}"
       owner: root
       group: root
    with_items:
      - docker-compose.yml
      - Dockerfile
      - app.py
      - requirements.txt 

  - name: checar imagem
    #command: "docker image ls | grep impacta"
    command: docker image ls --filter reference='impacta*'
    register: docker_check
  - debug: msg={{ docker_check }}

  - name: Construindo a imagem
    command: docker build -t impacta_app:1.0 .
    args:
       chdir: /root/
    register: docker_build
    tags:
      - docker-build

  - name: Executando o docker-compose
    command: docker-compose up -d
    args:
       chdir: /root/
    register: docker_compose_up
    tags:
      - docker-start
